# Generated by Django 4.0.10 on 2023-04-06 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('comment', models.TextField(null=True)),
                ('specs', models.TextField(null=True)),
                ('date_acquired', models.DateField(blank=True, null=True, verbose_name='Purchase date')),
                ('date_sold', models.DateField(blank=True, null=True, verbose_name='Sale date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bike_image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
