# Generated by Django 4.0.10 on 2023-04-06 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wheelset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('comments', models.TextField(null=True)),
                ('date_acquired', models.DateField(blank=True, null=True, verbose_name='Purchase date')),
                ('date_sold', models.DateField(blank=True, null=True, verbose_name='Sale date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='wheel_image')),
                ('bike', models.ManyToManyField(to='bike.bike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wheelset',
                'verbose_name_plural': 'Wheelsets',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('content', models.TextField()),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='bike.bike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
