# Generated by Django 4.0.10 on 2023-04-09 20:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bike', '0002_wheelset_maintenance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bike',
            new_name='BikeDetail',
        ),
    ]
