# Generated by Django 4.0.10 on 2023-04-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_rename_wheelset_wheelsets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikedetail',
            old_name='description',
            new_name='bike_description',
        ),
        migrations.RenameField(
            model_name='bikedetail',
            old_name='name',
            new_name='bike_name',
        ),
        migrations.RenameField(
            model_name='bikedetail',
            old_name='comment',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='wheelsets',
            old_name='name',
            new_name='wheels_name',
        ),
    ]
