# Generated by Django 4.0.10 on 2023-04-09 20:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bike', '0004_rename_wheelset_wheelsets'),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ride',
            new_name='RideDetail',
        ),
    ]
