# Generated by Django 4.0.10 on 2023-04-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_rename_ride_ridedetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ridedetail',
            old_name='bike',
            new_name='bike_name',
        ),
        migrations.RenameField(
            model_name='ridedetail',
            old_name='comment',
            new_name='ride_comment',
        ),
        migrations.RenameField(
            model_name='ridedetail',
            old_name='date',
            new_name='ride_date',
        ),
        migrations.RenameField(
            model_name='ridedetail',
            old_name='distance',
            new_name='ride_distance',
        ),
        migrations.RenameField(
            model_name='ridedetail',
            old_name='name',
            new_name='ride_name',
        ),
        migrations.RenameField(
            model_name='ridedetail',
            old_name='time',
            new_name='ride_time',
        ),
        migrations.RenameField(
            model_name='ridedetail',
            old_name='tss',
            new_name='ride_tss',
        ),
    ]
